### ISSUE TITLE
Deal with concurrent queries.

### ISSUE THREAD

**Issue by cdawei** [cdawei/path_vis#6]
From @berebere86:
It seems that no one else can access the demo page while it is processing another query... 
we could consider:
1) change server.py to support multithreading.
2) use a stable web platform (such as AngularJS or Backbone?)
3) limit the query to use only small number of POIs

**Comment by cdawei** [comment]
The root cause of this problem is the current simple server (i.e. server.py) does not support multi-threading, I assume option 1 can solve this problem.

**Comment by chengsoonong** [comment]
https://kdecherf.com/blog/2012/07/29/multithreaded-python-simple-http-server/

**Comment by cdawei** [comment]
I incorporated Cheng's suggestions above, but no idea how to test it.

**Comment by shinminjeong** [comment]
Hi @cdawei, I pulled your latest commit to the live demo page. but seems like multi-threading is still not working. You can test this by accessing from another page while processing in one page.

I actually tried option2 for a few days and successfully moved the app on the django platform to support multi-threading (started a new branch: django-server). I will be running the live demo based on this until another update is available.

**Comment by cdawei** [comment]
> but seems like multi-threading is still not working. 

It seems that I was out of luck :-1: 

> tried option2 for a few days and successfully moved the app on the django platform to support multi-threading

Thanks very much for this effort @berebere86 :+1: 

> started a new branch: django-server

As this branch works for concurrent queries, I'll try to merge it with branch: master

**Comment by cdawei** [comment]
resolved in pull request #7
